"""Declarative base and the mixins every table uses.

Two things are decided here that are painful to change later: how constraints are
named, and what a primary key is.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Alembic's autogenerate compares what the database has against what the metadata
# describes. Postgres names unnamed constraints itself, in a form the metadata
# cannot predict, so a later migration has nothing to drop them by. Fixing the
# convention up front is the difference between a reversible migration and a
# hand-written one.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKey:
    """A UUID primary key, generated by the application.

    Not a serial: identifiers appear in URLs and in API responses, and a sequential
    integer leaks how many rows exist and lets one tenant guess another's ids.

    Generated by the application at flush rather than by a database default, so
    the value does not depend on a server-side function being present — which
    matters when a migration or a fixture inserts rows.
    """

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)


class Timestamps:
    """Created and updated times, both set by the database.

    `server_default`/`onupdate` at the database rather than in Python: rows written
    by a migration or a maintenance script get the same treatment, and the clock is
    the database's rather than each process's.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
